//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSaper.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfSaper.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string AboutWindow_ButtonClose_Text {
            get {
                return ResourceManager.GetString("AboutWindow_ButtonClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string AboutWindow_LabelAuthor_Text {
            get {
                return ResourceManager.GetString("AboutWindow_LabelAuthor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project site: .
        /// </summary>
        public static string AboutWindow_LabelProjectSite_Text {
            get {
                return ResourceManager.GetString("AboutWindow_LabelProjectSite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string AboutWindow_LabelVersion_Text {
            get {
                return ResourceManager.GetString("AboutWindow_LabelVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bombs: .
        /// </summary>
        public static string ConfigWindow_OptionCustom_BombsCount_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_OptionCustom_BombsCount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H_orizontal Tiles: .
        /// </summary>
        public static string ConfigWindow_OptionCustom_HorizontalTiles_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_OptionCustom_HorizontalTiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Custom.
        /// </summary>
        public static string ConfigWindow_OptionCustom_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_OptionCustom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vertical Tiles: .
        /// </summary>
        public static string ConfigWindow_OptionCustom_VerticalTiles_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_OptionCustom_VerticalTiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Easy.
        /// </summary>
        public static string ConfigWindow_OptionEasy_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_OptionEasy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hard.
        /// </summary>
        public static string ConfigWindow_OptionHard_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_OptionHard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Normal.
        /// </summary>
        public static string ConfigWindow_OptionNormal_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_OptionNormal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start new game.
        /// </summary>
        public static string ConfigWindow_StartGameButton_Text {
            get {
                return ResourceManager.GetString("ConfigWindow_StartGameButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game Settings.
        /// </summary>
        public static string ConfigWindow_Title {
            get {
                return ResourceManager.GetString("ConfigWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current flags count.
        /// </summary>
        public static string MainWindow_CurrentFlagCount_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFlagCount_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tile is not part of the game!.
        /// </summary>
        public static string MainWindow_HeyMessage {
            get {
                return ResourceManager.GetString("MainWindow_HeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey :).
        /// </summary>
        public static string MainWindow_HeyMessage_Title {
            get {
                return ResourceManager.GetString("MainWindow_HeyMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over! One more time?.
        /// </summary>
        public static string MainWindow_Message_GameLost_Text {
            get {
                return ResourceManager.GetString("MainWindow_Message_GameLost_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost :(.
        /// </summary>
        public static string MainWindow_Message_GameLost_Title {
            get {
                return ResourceManager.GetString("MainWindow_Message_GameLost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minefield cleared. You won! One more time?.
        /// </summary>
        public static string MainWindow_Message_GameWon_Text {
            get {
                return ResourceManager.GetString("MainWindow_Message_GameWon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won :).
        /// </summary>
        public static string MainWindow_Message_GameWon_Title {
            get {
                return ResourceManager.GetString("MainWindow_Message_GameWon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string MainWindow_RestartButton_Text {
            get {
                return ResourceManager.GetString("MainWindow_RestartButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF Saper.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total bombs count.
        /// </summary>
        public static string MainWindow_TotalBombsCount_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_TotalBombsCount_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Game.
        /// </summary>
        public static string MenuItem_Game {
            get {
                return ResourceManager.GetString("MenuItem_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings....
        /// </summary>
        public static string MenuItem_GameConfig {
            get {
                return ResourceManager.GetString("MenuItem_GameConfig", resourceCulture);
            }
        }
    }
}
